train_dataset: cifar-fs
train_dataset_args: {split: train, augment: crop}
test_fs_dataset: cifar-fs
test_fs_dataset_args: {split: test}
test_eval_fs_epoch: 100
eval_fs_args: {n_way: 5, n_shots: [1], n_query: 15, n_task: 200}
# val_fs_dataset: cifar-fs
# val_fs_dataset_args: {split: val}
# val_eval_fs_epoch: 100

model: classifier
model_args:
    encoder: resnet12
    encoder_args: {}
    classifier: nn-classifier 
    classifier_args: {n_classes: 64}

batch_size: 128
max_epoch: 100
optimizer: sgd
optimizer_args: {lr: 0.05, weight_decay: 5.e-4, milestones: [60,80]}
fs_iters: 5

save_epoch: 1
adversary: 
    eps: 8
    alpha: 2
    iters: 7
    norm: inf
als:
    gamma: 0.1
    eta: 0.9
    minval: 0
    maxval: 1
    inner: True
fs_attack:
    eps: 8
    alpha: 2
    iters: 7
    norm: inf
# val_attack: 
#     eps: 8
#     alpha: 2
#     iters: 7
#     norm: inf